name: webextdev
version: 0.1.0
description: Helps to develop browser extensions for Chrome, Edge, and Firefox.
homepage: https://github.com/terrier989/webext
author: terrier989 <terrier989@gmail.com>

commands:
  webextdev:

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  test: ^1.6.0
  test_api: ^0.2.0
  webext: '>=0.1.0 <1.0.0'
  webdev: ^2.3.0

dev_dependencies:
  pedantic: ^1.8.0

# dependency_overrides:
#  webext:
#    path: ../webext