name: webextdev
version: 0.1.3
description:
  A command-line tool for developing browser extensions. Supports Chrome, Edge, and Firefox.
homepage: https://github.com/terrier989/webext
author: terrier989 <terrier989@gmail.com>

executables:
  webextdev:

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  archive: '>=2.0.0 <3.0.0'
  args: '>=1.5.2 <2.0.0'
  io: '>=0.3.3 <1.0.0'
  test: '>=1.6.0 <2.0.0'
  test_api: '>=0.2.0 <1.0.0'
  webext: '>=0.1.0 <1.0.0'
  webdev: '>=2.3.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0