name: example
version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  webext: any

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  pedantic: any
  test: any
  webdev: ^2.3.0
  webextdev: any
